-- Optional seed file used by Neon Launchpad / vite-plugin-neon-new.
-- Schema is managed by Drizzle migrations (`bun run db:push`).
-- Admin users and demo data: `bun run db:seed` (see .env.example).
