/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as FSlugRouteImport } from './routes/f/$slug'
import { Route as ApiInngestRouteImport } from './routes/api/inngest'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminFormsFormIdRouteImport } from './routes/admin/forms/$formId'
import { Route as AdminFormsFormIdSubmissionsRouteImport } from './routes/admin/forms/$formId.submissions'
import { Route as AdminFormsFormIdSubmissionsSubmissionIdRouteImport } from './routes/admin/forms/$formId.submissions.$submissionId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const FSlugRoute = FSlugRouteImport.update({
  id: '/f/$slug',
  path: '/f/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFormsFormIdRoute = AdminFormsFormIdRouteImport.update({
  id: '/forms/$formId',
  path: '/forms/$formId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormsFormIdSubmissionsRoute =
  AdminFormsFormIdSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AdminFormsFormIdRoute,
  } as any)
const AdminFormsFormIdSubmissionsSubmissionIdRoute =
  AdminFormsFormIdSubmissionsSubmissionIdRouteImport.update({
    id: '/$submissionId',
    path: '/$submissionId',
    getParentRoute: () => AdminFormsFormIdSubmissionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/api/$': typeof ApiSplatRoute
  '/api/inngest': typeof ApiInngestRoute
  '/f/$slug': typeof FSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/forms/$formId': typeof AdminFormsFormIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/admin/forms/$formId/submissions': typeof AdminFormsFormIdSubmissionsRouteWithChildren
  '/admin/forms/$formId/submissions/$submissionId': typeof AdminFormsFormIdSubmissionsSubmissionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/api/$': typeof ApiSplatRoute
  '/api/inngest': typeof ApiInngestRoute
  '/f/$slug': typeof FSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/forms/$formId': typeof AdminFormsFormIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/admin/forms/$formId/submissions': typeof AdminFormsFormIdSubmissionsRouteWithChildren
  '/admin/forms/$formId/submissions/$submissionId': typeof AdminFormsFormIdSubmissionsSubmissionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/api/$': typeof ApiSplatRoute
  '/api/inngest': typeof ApiInngestRoute
  '/f/$slug': typeof FSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/forms/$formId': typeof AdminFormsFormIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/admin/forms/$formId/submissions': typeof AdminFormsFormIdSubmissionsRouteWithChildren
  '/admin/forms/$formId/submissions/$submissionId': typeof AdminFormsFormIdSubmissionsSubmissionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/leads'
    | '/api/$'
    | '/api/inngest'
    | '/f/$slug'
    | '/admin/'
    | '/admin/forms/$formId'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/admin/forms/$formId/submissions'
    | '/admin/forms/$formId/submissions/$submissionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/leads'
    | '/api/$'
    | '/api/inngest'
    | '/f/$slug'
    | '/admin'
    | '/admin/forms/$formId'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/admin/forms/$formId/submissions'
    | '/admin/forms/$formId/submissions/$submissionId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/leads'
    | '/api/$'
    | '/api/inngest'
    | '/f/$slug'
    | '/admin/'
    | '/admin/forms/$formId'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/admin/forms/$formId/submissions'
    | '/admin/forms/$formId/submissions/$submissionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiInngestRoute: typeof ApiInngestRoute
  FSlugRoute: typeof FSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/f/$slug': {
      id: '/f/$slug'
      path: '/f/$slug'
      fullPath: '/f/$slug'
      preLoaderRoute: typeof FSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/forms/$formId': {
      id: '/admin/forms/$formId'
      path: '/forms/$formId'
      fullPath: '/admin/forms/$formId'
      preLoaderRoute: typeof AdminFormsFormIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forms/$formId/submissions': {
      id: '/admin/forms/$formId/submissions'
      path: '/submissions'
      fullPath: '/admin/forms/$formId/submissions'
      preLoaderRoute: typeof AdminFormsFormIdSubmissionsRouteImport
      parentRoute: typeof AdminFormsFormIdRoute
    }
    '/admin/forms/$formId/submissions/$submissionId': {
      id: '/admin/forms/$formId/submissions/$submissionId'
      path: '/$submissionId'
      fullPath: '/admin/forms/$formId/submissions/$submissionId'
      preLoaderRoute: typeof AdminFormsFormIdSubmissionsSubmissionIdRouteImport
      parentRoute: typeof AdminFormsFormIdSubmissionsRoute
    }
  }
}

interface AdminFormsFormIdSubmissionsRouteChildren {
  AdminFormsFormIdSubmissionsSubmissionIdRoute: typeof AdminFormsFormIdSubmissionsSubmissionIdRoute
}

const AdminFormsFormIdSubmissionsRouteChildren: AdminFormsFormIdSubmissionsRouteChildren =
  {
    AdminFormsFormIdSubmissionsSubmissionIdRoute:
      AdminFormsFormIdSubmissionsSubmissionIdRoute,
  }

const AdminFormsFormIdSubmissionsRouteWithChildren =
  AdminFormsFormIdSubmissionsRoute._addFileChildren(
    AdminFormsFormIdSubmissionsRouteChildren,
  )

interface AdminFormsFormIdRouteChildren {
  AdminFormsFormIdSubmissionsRoute: typeof AdminFormsFormIdSubmissionsRouteWithChildren
}

const AdminFormsFormIdRouteChildren: AdminFormsFormIdRouteChildren = {
  AdminFormsFormIdSubmissionsRoute:
    AdminFormsFormIdSubmissionsRouteWithChildren,
}

const AdminFormsFormIdRouteWithChildren =
  AdminFormsFormIdRoute._addFileChildren(AdminFormsFormIdRouteChildren)

interface AdminRouteChildren {
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminFormsFormIdRoute: typeof AdminFormsFormIdRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLeadsRoute: AdminLeadsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminFormsFormIdRoute: AdminFormsFormIdRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiInngestRoute: ApiInngestRoute,
  FSlugRoute: FSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
